Adding package docs, inline comments for readability, testing, client, docker examples
epi-project/socksx pull request #1
Opened 2023-09-27 14:50 UTC by anmolbhatia05

Stats - 
- Testing coverage improved from 3% in socksx to 25%.

2023-09-29 14:06 UTC, Lut99 requested changes
Overall, great work! The `socksx`-crate instantly got bumped from a really mysterious crate to a very workable one! :D

I've left quite a few comments, but not everything is necessary to merge the PR, just for if you have more time and like this kind of work. Anything you've already done is amazing :) I marked the ones I think we have to address, but that can also be by disagreeing with me ;)

2023-09-29 14:06 UTC, Lut99 commented on Dockerfile
> +FROM ubuntu:23.10
\[**check**\] Is there a particular reason that you're depending on 23.10? If you're just looking for libssl3, I think that 22.04 already has that - and that's an LTS release so it can be expected to receive security updates for longer :)

2023-09-29 14:06 UTC, Lut99 commented on Dockerfile.counter
> +# This won't build on Mac OS X. Try on Linux or Windows.
\[**check**\] Ah, interesting! Why is that, is it because of ARM VS x86-64 issues? If so, perhaps it's good to be specific that it's the case (i.e., Intel-based macs might still work).

2023-09-29 14:06 UTC, Lut99 commented on Dockerfile.encrypt-decrypt
> +FROM ubuntu:23.10
\[**check**\] Same as above, consider using an LTS release if possible

2023-09-29 14:06 UTC, Lut99 commented on docker-compose-extensive.yml
> +  proxy-main:
If you wanna be super fancy, consider adding a [dependency](https://docs.docker.com/compose/compose-file/compose-file-v3/#depends_on) to this service such that it won't start until the others are started :)

2023-09-29 14:06 UTC, Lut99 commented on docker-compose-extensive.yml
> +  proxy-other:
Same as above

2023-09-29 14:06 UTC, Lut99 commented on examples/client/Cargo.toml
\[**check**\] So there is a bit of a design space here, but Cargo has a specific [example](http://xion.io/post/code/rust-examples.html)-feature, which is the more canonical way to add an example like this. If you pulled it separately just for dependency's sake, consider adding the required dependencies as a `dev-dependency` in the relevant package's `Cargo.toml`; otherwise, if you want to strengthen that it's a separate package people might use for other purposes than an example, consider moving it outside of the example folder and adding it to the workspace (i.e., toplevel Cargo.toml file).

2023-09-29 14:06 UTC, Lut99 commented on socksx/examples/client.rs
> +/// Connects to a destination using SOCKS5 protocol.
Well, there's no need to :), but I tend to write function docstrings a bit more verbose to communicate what arguments and returns values do as well. See the suggestion for an example. But I get this may also be way too much effort xD and what you have is most certainly better than nothing

```suggestion
/// Connects to a destination through a proxy using SOCKS5 protocol, then sends an example message through the network tunnel.
/// 
/// # Arguments
/// - `proxy_addr`: The address of the SOCKS5 proxy through which the traffic will be tunnelled.
/// - `dest_addr`: The address to which the traffic should be sent after the proxy.
/// 
/// # Errors
/// This function can error if we failed to connect to the given proxy or failed to send it an example message.
```

2023-09-29 14:06 UTC, Lut99 commented on socksx/src/common/constants.rs
Very good commenting! :D

2023-09-29 14:06 UTC, Lut99 commented on socksx/src/common/credentials.rs
> +    /// # Parameters
Ah, very nice :)

2023-09-29 14:06 UTC, Lut99 commented on socksx/src/lib.rs
> +//! For SOCKS version 5, chaining is not supported yet. It will be added in the future. Eg. Client -> Socks5 -> Destination
I'd actually expected the example to show what _wasn't_ possible, so I was confused for a second... You could just strengthen this is what is allowed only or example what isn't allowed.

2023-09-29 14:06 UTC, Lut99 commented on socksx/src/common/util.rs
>  pub async fn resolve_addr<S: Into<String>>(addr: S) -> Result<SocketAddr> {
This one is unit testable, if you're looking for more (check out the [`#[tokio::test]`](https://docs.rs/tokio-macros/latest/tokio_macros/attr.test.html) macro for testing async functions)

2023-09-29 14:06 UTC, Lut99 commented on socksx/src/main.rs
Could you maybe add a header comment here specifying what the goal is of this binary as a whole? When looking through the files, it seems a bit indistinguishable from the examples... :#

2023-09-29 14:06 UTC, Lut99 commented on socksx/examples/client.rs
If you're bored, you could add a header comment here briefly explaining what the purpose is of this example.

2023-09-29 14:06 UTC, Lut99 commented on socksx/examples/functions.rs
Same here about the header comment

2023-09-29 14:06 UTC, Lut99 commented on socksx/examples/redirector.rs
Same here about the header comment

2023-09-29 14:06 UTC, Lut99 commented on socksx/src/socks6/chain.rs
> +        assert_eq!(chain.links.len(), 2); // Should include root and the new link
You could probably make this comment explicit by comparing the links with a static list :)

2023-09-29 14:06 UTC, Lut99 commented on socksx/src/socks6/mod.rs
\[**check**\] You could add a few tests for constructors or deconstructors for the Socks6Request. Most interesting I'd find the `into_socks_bytes()`, especially since you do test it in other places (constructors and destructors are often trivial, but for consistency with other files you could add them here).

Same for `into_socks_bytes()` for a few of the other structs, unless there is some reason these cannot be done as a unit test.

2023-09-29 14:06 UTC, Lut99 commented on socksx/src/socks6/options.rs
> +    // fn test_from_socks_bytes_auth_method_advertisement() {
Ah, hmm, is there a reason that you commented this test? Is something preventing you from doing this as a unit test?

2023-09-29 14:06 UTC, Lut99 commented on socksx/examples/client.rs
> +/// Connects to a destination using SOCKS5 protocol.
I see later on you did this in other places, awesome! Still, you could do something similar here for consistency if you're still willing to write them

2023-09-29 14:06 UTC, Lut99 commented on docker-compose-extensive.yml
> +networks:
\[**check**\] Is there a particular reason that this virtual network is required? If so, then it's good to comment why it's useful.

2023-09-29 14:06 UTC, Lut99 commented on README.md
> +## TODO
Nice :)

2023-09-30 11:33 UTC, anmolbhatia05 commented on Dockerfile
> +FROM ubuntu:23.10
No reason in particular, just went with the latest without thinking much. However, I agree with your point and will change it.

2023-09-30 11:35 UTC, anmolbhatia05 commented on Dockerfile.encrypt-decrypt
> +FROM ubuntu:23.10
I will change it.

2023-09-30 16:10 UTC, anmolbhatia05 commented on docker-compose-extensive.yml
> +  proxy-main:
Thanks for the suggestion. I have used it.

2023-09-30 19:42 UTC, anmolbhatia05 commented on docker-compose-extensive.yml
> +networks:
The reason why I created a virtual network was to give the destination container a virtual ip address and give it to the client when I make the request.

2023-09-30 19:42 UTC, anmolbhatia05 commented on examples/client/Cargo.toml
The reason why I want it is for an example (of how to use socksx interface) and testing sake. Testing the chains or sockies in general. What do you think is the best way for this ?

2023-09-30 19:42 UTC, anmolbhatia05 commented on socksx/examples/client.rs
Good point.

2023-09-30 19:42 UTC, anmolbhatia05 commented on socksx/examples/client.rs
> +/// Connects to a destination using SOCKS5 protocol.
Thank you for the example.

2023-09-30 19:42 UTC, anmolbhatia05 commented on socksx/src/socks6/options.rs
> +    // fn test_from_socks_bytes_auth_method_advertisement() {
My bad, uncommented and finished it

2023-09-30 19:42 UTC, anmolbhatia05 commented on socksx/src/common/util.rs
>  pub async fn resolve_addr<S: Into<String>>(addr: S) -> Result<SocketAddr> {
Thank you for the suggestion. I created this one.

2023-09-30 19:42 UTC, anmolbhatia05 commented on socksx/src/lib.rs
> +//! For SOCKS version 5, chaining is not supported yet. It will be added in the future. Eg. Client -> Socks5 -> Destination
Fair point. Thanks.

2023-09-30 19:42 UTC, anmolbhatia05 commented on Dockerfile.counter
> +# This won't build on Mac OS X. Try on Linux or Windows.
Yes, it works on intel based macs.

2023-10-02 09:37 UTC, Lut99 commented on examples/client/Cargo.toml
Yeah, I'd use the Cargo example-feature for that. It's exactly for these cases where docstring-examples are too brief and/or it's not testable in a unit test, but you still want to use it for example/testing purposes. It's a normal binary, then, but you can then run it conveniently using `cargo run --example <...>`, and people will be looking for it to be here if they're investigating the crate.

2023-10-02 11:04 UTC, Lut99 approved these changes
Awesome, looks amazing! Thanks :D

2023-10-02 11:05 UTC, merged